---
title: "Circadian_phase_enrichment_analysis"
output: html_document
date: "2020-08-13"
---

# PacBio Data Analysis Notes - Circadian phase enrichment analysis

### load packages
```{r}
library(tidyverse)
library(ggplot2)
```

I wrote a function called *Phase_fisher* to draw the plots.
```{r}
# The "Cycler" argument requires a dataframe as an input. The "dataset" argument is just a brief description of the input data.
Phase_fisher <- function(Cycler, dataset) {
  # first, you need to load the list of genes expressed or DSed.
  expressed_gene_DSG_xct2 <- read_tsv("path to the file") # change the path
  
  sigFeatures_position_col_xct2 <- read_tsv("path to the file", 
                                            col_names = c("feature", "chr", "start", "end", "log2FCvst", "padjust")) %>% 
    separate(feature, into = c("locus", "element"), sep = ":") %>%
    mutate(change = ifelse(log2FCvst>0, "up_regulated", "down_regulated")) %>% 
    mutate(fraction = str_remove(element, "[0-9]{1,3}$")) # %>%  # remove the numbers in each element id

  Cycler <- Cycler %>%  
    filter(AGI %in% expressed_gene_DSG_xct2$geneID)  # only to include genes expressedin Junction Seq 

  xct2_Cycling <- Cycler %>% 
    filter(AGI %in% sigFeatures_position_col_xct2$locus)
  fisher_xct2_Cycling <- left_join(data.frame(table(factor(round(xct2_Cycling$phase/3-0.5)*3, levels = 0:24))),
                                  data.frame(table(factor(round(Cycler$phase/3-0.5)*3, levels = 0:24))),
                                  by = 'Var1')    # aggregrate gene counts by 3h intervals (may have a better way to do this)
  
  for (i in 1:length(fisher_xct2_Cycling$Var1)) {
    c1 <- fisher_xct2_Cycling$Freq.x[i]
    c2 <- fisher_xct2_Cycling$Freq.y[i] - c1
    c3 <- sum(fisher_xct2_Cycling$Freq.x[-i])
    c4 <- sum(fisher_xct2_Cycling$Freq.y[-i]) - c3
    matrix_c <- matrix(c(c1, c2, c3 , c4), 2, 2,
                            dimnames = list(`xct-2`=c("DS", "not.DS"),
                                            phase = c("Yes", "No")))
    fisher_xct2_Cycling$p.value[i] <- fisher.test(matrix_c,alternative = "greater")$p.value
  }
  
  fisher_plot <- fisher_xct2_Cycling %>% 
    ggplot(mapping = aes(x=as.numeric(Var1), y=-log10(p.value))) + 
    geom_col(aes(fill = p.value<0.05),width = 3) +
    labs(x="Phase", y="-log10(p.value)", title = paste0("Phase Enrichment of Differentially Spliced Genes in xct-2\n", dataset))
  print(fisher_plot)
}  
```

### Load data and run the function. Here's an example.
```{r}
# format the data (because the colnames of each dataset are very different)
Covington_Cycling <- read_csv("path to the file", col_names = T) %>% 
  filter(`CIRCADIAN?`==1) %>% 
  dplyr::rename(AGI=LOCUS,    # change some col names to fit the vector names in the function
         phase=Phase)  

Phase_fisher(Covington_Cycling,"Covington 2007")
```

